# .goreleaser.yaml
# GoReleaser configuration for dotsync
# Documentation: https://goreleaser.com/customization/

version: 2

project_name: dotsync

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: dotsync
    main: ./cmd/dotsync
    binary: dotsync
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: dotsync
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^style:'
      - '^refactor:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: wtfzambo
    name: dotsync
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Tag}}"

# Disable homebrew for now (user can add later)
# brews:
#   - name: dotsync
#     repository:
#       owner: wtfzambo
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/wtfzambo/dotsync
#     description: "CLI tool for syncing config files across machines via cloud storage"
#     license: MIT
#     test: |
#       system "#{bin}/dotsync --version"
