version: '3'

vars:
  BINARY: dotsync
  BUILD_DIR: bin

tasks:
  default:
    desc: Build the binary
    cmds:
      - task: build

  build:
    desc: Build the binary with optimizations
    cmds:
      - go build -ldflags "-s -w -X main.version=$(git describe --tags --always --dirty 2>/dev/null || echo 'dev') -X main.commit=$(git rev-parse --short HEAD 2>/dev/null || echo 'none') -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X main.builtBy=task" -o {{.BUILD_DIR}}/{{.BINARY}} ./cmd/dotsync
    sources:
      - '**/*.go'
    generates:
      - '{{.BUILD_DIR}}/{{.BINARY}}'

  dev:
    desc: Build the binary without optimizations (faster)
    cmds:
      - go build -ldflags "-X main.version=dev -X main.commit=$(git rev-parse --short HEAD 2>/dev/null || echo 'none') -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X main.builtBy=task" -o {{.BUILD_DIR}}/{{.BINARY}} ./cmd/dotsync

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:cover:
    desc: Run tests with coverage report
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  run:
    desc: Build and run the binary
    deps: [build]
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY}} {{.CLI_ARGS}}

  install:
    desc: Install the binary to GOPATH/bin
    deps: [build]
    cmds:
      - cp {{.BUILD_DIR}}/{{.BINARY}} $(go env GOPATH)/bin/

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run ./...
